name: Manual Release JAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Verify Docker is available
        run: |
          echo "Docker info:"
          docker info

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

      - name: Create JWT_SECRET
        run: echo "JWT_SECRET=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c32)" >> $GITHUB_ENV

      - name: Run tests (with Testcontainers)
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
          TESTCONTAINERS_RYUK_DISABLED: "true"
          TESTCONTAINERS_STARTUP_TIMEOUT: "120000"
        run: |
          ./gradlew clean build --info

      - name: Extract version
        id: get_version
        run: |
          echo "version=$(grep -oP 'version\\s*=\\s*\"\\K[^\"]+' build.gradle.kts)" >> $GITHUB_OUTPUT

      - name: Publish JAR as Release
        if: success() && github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}