name: Manual Release JAR

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

      - name: Extract version from Gradle
        id: get_version
        run: |
          VERSION=$(grep -oP 'version\s*=\s*"\K[^"]+' build.gradle.kts)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build fatJar
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
          TESTCONTAINERS_RYUK_DISABLED: "true"
          TESTCONTAINERS_STARTUP_TIMEOUT: "120000"
          JWT_SECRET: "DummyJWT"
        run: ./gradlew clean build

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_version.outputs.version }}
          tag_name: ${{ steps.get_version.outputs.version }}
          body: |
            Automatic release for version `${{ steps.get_version.outputs.version }}`
          files: |
            build/libs/*${{ steps.get_version.outputs.version }}*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
